#!/bin/csh

#foreach pack ( classall  classify  select  sifdecoder )

#foreach pack ( classall )
#foreach pack ( classify )
#foreach pack ( select )
foreach pack ( sifdecoder )
  echo "    " $pack
  echo "      .. making pdf"
  pdfroff -e -m man $pack.1 > ../../doc/pdf/$pack.pdf
  echo "      .. making html"
  groff -e -m man -T html -P "-Istem $pack-" -P "-i150" $pack.1 \
    > ${SIFDECODE}/doc/html/$pack.html
  mv *.png ${SIFDECODE}/doc/html
end


