name: Meson
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: SIFDecode/${{ matrix.os }}/${{ matrix.compiler }}-v${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        version: ['12']
        include:
          - compiler: gcc
          - os: ubuntu-latest
            compiler: intel-classic
            version: '2021.10'
          - os: ubuntu-latest
            compiler: intel
            version: '2023.2'
          - os: macos-latest
            compiler: gcc
            version: '13'
            arch: 'arm64'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out SIFDecode
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Meson and Ninja
        run: pip install meson ninja

      - name: Install compilers
        uses: fortran-lang/setup-fortran@main
        with:
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}

      # Uncomment this section to obtain ssh access to VM
      # - name: Setup tmate session
      # if: matrix.os == 'windows-latest'
      # uses: mxschmitt/action-tmate@v3

      - name: Setup SIFDecode
        shell: bash
        run: |
          meson setup builddir --prefix=$GITHUB_WORKSPACE/../meson

      - name: Build SIFDecode
        shell: bash
        run: |
          meson compile -C builddir
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}_${{ matrix.compiler }}-v${{ matrix.version }}_meson-log.txt
          path: builddir/meson-logs/meson-log.txt

      - name: Install SIFDecode
        shell: bash
        run: |
          meson install -C builddir
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.os }}_${{ matrix.compiler }}-v${{ matrix.version }}_install-log.txt
          path: builddir/meson-logs/install-log.txt
